# Generated by Django 3.0 on 2019-12-22 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('type', models.PositiveIntegerField(choices=[(0, 'HTML'), (1, '最新文章'), (2, '最热文章'), (3, '最新评论')], default=0, verbose_name='类型')),
                ('status', models.PositiveIntegerField(choices=[(0, '隐藏'), (1, '展示')], default=1, verbose_name='栏目')),
                ('content', models.CharField(blank=True, help_text='如果设置的不是HTML类型，评论可为空', max_length=500, verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '侧栏',
                'verbose_name_plural': '侧栏',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('href', models.URLField(verbose_name='链接')),
                ('status', models.PositiveIntegerField(choices=[(0, '删除'), (1, '正常')], default=1, verbose_name='状态')),
                ('created_name', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='权重越高，展示顺序越靠前', verbose_name='搜索权重')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
    ]
